version: "3"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
      # Uncomment for logging all SQL statements
      # command: ["postgres", "-c", "log_statement=all"]
  api:
    image: apollo-objekts
    environment:
      - DB_NAME
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS
      - GQL_PORT
    ports:
      - "${GQL_PORT}:${GQL_PORT}"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db
  processor:
    image: apollo-objekts
    environment:
      - DB_NAME
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS
      - ALCHEMY_KEY
    command: ["sqd", "process:prod"]
    depends_on:
      - db
